module PfrpgClasses
end

require 'pfrpg_classes/heroclass'
require 'pfrpg_classes/heroclass/barbarian'
require 'pfrpg_classes/heroclass/bard'
require 'pfrpg_classes/heroclass/cleric'
require 'pfrpg_classes/heroclass/druid'
require 'pfrpg_classes/heroclass/fighter'
require 'pfrpg_classes/heroclass/monk'
require 'pfrpg_classes/heroclass/paladin'
require 'pfrpg_classes/heroclass/ranger'
require 'pfrpg_classes/heroclass/rogue'
require 'pfrpg_classes/heroclass/sorcerer'
require 'pfrpg_classes/heroclass/wizard'
require 'pfrpg_classes/heroclass/arcane_archer'
require 'pfrpg_classes/heroclass/arcane_trickster'
require 'pfrpg_classes/heroclass/assassin'
require 'pfrpg_classes/heroclass/duelist'
require 'pfrpg_classes/heroclass/dragon_disciple'
require 'pfrpg_classes/heroclass/eldritch_knight'
require 'pfrpg_classes/heroclass/loremaster'
require 'pfrpg_classes/heroclass/mystic_theurge'
require 'pfrpg_classes/heroclass/pathfinder_chronicler'
require 'pfrpg_classes/heroclass/shadowdancer'